<template>
<div>
    <v-container grid-list-xs>
        <v-row>
            <v-col align="center">
            <h1 style="color:#EC5713" class="compHead">SPEAKERS</h1>
            <v-divider></v-divider>
            </v-col>
        </v-row>
        <v-container class="pa-5" >
        <carousel :per-page-custom="responsive" :pagination-enabled="false" :navigation-enabled="true" :scrollPerPage="false" :navigate-to="[slideshow,true]"	>
            <slide v-for="(speaker, index) in speakers" :key="index" :id="index" >
                 <v-hover v-slot="{ hover }">
                    <v-card class="mx-auto" color="grey lighten-4" max-width="300">
                    <v-img aspect-ratio="1"  :src="'../../'+speaker.src" gradient="to top right, rgba(100,115,201,.33), rgba(25,32,72,.7)">
                        <div class="d-flex v-card--reveal-first white--text"
                                style="height: 80%"
                                v-if="!hover"
                            >
                            <b>{{speaker.name}}</b>
                        </div>
                        <v-expand-transition>
                            <v-overlay  v-if="hover" color="indigo darken-3" class="transition-easy-in-easy-out v-card--reveal white--text  pa-3"
                                style="height: 100%;">
                                <span style="text-align:left" class="cvtext" >{{speaker.cv}}</span>
                            </v-overlay >
                        </v-expand-transition>
                    </v-img>
                    </v-card>
                </v-hover>
            </slide>
        </carousel>
        </v-container>
    </v-container>
</div>  
</template>
<script>
import { Carousel, Slide } from 'vue-carousel';
export default {
    data() {
        return {
            overlay: false,
            selectslide:5,
            speakers: [
                {name:"Mohamed Jouahri",cv:"General Manager of Casablanca Event and Animation.",
                  src:"mohamed.png"},
                {name:"Hakima Fasly",cv:"Vice-President of the Council of the City of Casablanca",
                  src:"hakima.png"},
                {name:"Aawatif Hayar",cv:"President of Hassan II University of Casablanca.",
                  src:"awatif.png",},
                {name:"Hassan Radoine",cv:"Director School of Architecture, Planning and Design of Mohammed VI Polytechnic University.",
                  src:"hassan.png",},
                {name:"Fabienne Goux-Baudiment",cv:"Doctor in social sciences and prospectivist.",
                  src:"fabien.png"},
                {name:"Cathal O'Madagain",cv:"Scientific director and assistant professor at the School of Collective Intelligence, UM6P. PhD in Philosophy from the University of Toronto.",
                  src:"cathal.png",},
                {name:"Remy Sietchiping",cv:"Chief of Policy, Legislation and Governance Section within the Urban Practices Branch of UN-Habitat. Ph.D in Geography from the University of Melbourne, Australia.",
                  src:"remy.png",},
                {name:"Monceyf Fadili",cv:"International expert in urban planning and territorial development.Former UN-Habitat Advisor.",
                  src:"monceyf.png",},
                {name:"Tridib Banerjee",cv:"Professor Emeritus of Public Policy, University of Southern California-USA.",
                  src:"tridib.png"},
                {name:"Rachel Armstrong",cv:"Professor of Experimental Architecture, University of Newcastle and Visiting Professor in the Department of Architecture, KU Leuven, Belgium.",
                  src:"rachel.png",},
                {name:"Giulio Verdini",cv:"Reader at the School of Architecture and Cities of the University of Westminster and Director of the BA Designing Cities: Planning and Architecture. He is also Visiting Professor at Mohammed VI Polytechnic University of Ben Guerir, in Morocco.",
                  src:"giulio.png",},
                {name:"Carlo Alberini",cv:"Architect and Urban Planner at Mohammed VI Polytechnic University with a PhD in Ports planning and waterfronts regeneration projects. He was a Fellow and Professor of Town Planning, Urban History, and Urban Management at the School of Architecture of Genoa and Florence.",
                  src:"carlo.png",},
                {name:"Matthew Hardy",cv:"Professor at Oxford University on the Sustainable Urban Development programme  and is Senior Lecturer and Direcor of Studies in Architecture and Urbanism at the Prince’s Foundation for Building Community.",
                  src:"matthew.png",},
                {name:"Saifur Rahman",cv:" Founding director of the Advanced Research Institute (www.ari.vt.edu) at Virginia Tech, USA where he is the Joseph R. Loring professor of electrical and computer engineering. He also directs the Center for Energy and the Global Environment (www.ceage.vt.edu). He is a Life Fellow of the IEEE and an IEEE Millennium Medal winner.",
                  src:"saifur.png",},
                {name:"Karima Echihabi",cv:"Research professor at the School of Computer Science of the Mohammed VI Polytechnic University in Morocco (UM6P). Her research interests are in data analysis, data series management and machine learning.",
                  src:"karima.png",},
                {name:"Hicham Bahi",cv:"Assistant Professor at the School of Architecture, Planning and Design, UM6P and holds a PhD in GIS and Remote Sensing.  He is among others the coordinator of the Territorial Performance Observatory project, the coordinator of doctoral training program of SAP+D and research team member of the urban metabolism project conducted jointly with MIT",
                  src:"hicham.png",},
                {name:"Mehdi Boukhari",cv:"Editor-in-chief of Editions Economiques, in charge of the Eco section of television news at 2M TV.",
                  src:"mehdi.png",}, 
                {name:"Lou Vasta",cv:"Lou Vasta, Founder & CEO, Vasta & Associates, Inc., CHICAGO, USA",
                  src:"lou.png",},
                {name:"Lamiae Benmakhlouf",cv:"Managing Director of MITC (Moroccan Information Technopark Company), Ms. Lamia Benmakhlouf has been working for 20 years in supporting entrepreneurship and innovation in high added value sectors.",
                  src:"lamiae.png",},
                {name:"Nicolas J.A. Buchoud",cv:"President of the Cercle Grand Paris for Sustainable Investment, co-founder of Renaissance Urbaine",
                  src:"nicolas.png",},
                {name:"Agnès Jullien",cv:"Vice- president international of Université Gustave Eiffel.Executive Director of the Forum of European Road Laboratories.",
                  src:"agnes.png"},
                {name:"Anass Kettani",cv:"Director of the Integration and Entrepreneurship Pole at Hassan II University in Casablanca. Deputy Director of the Biology and Health laboratory, Faculty of Sciences Ben Msik, Casablanca. Professor of Higher Education Hassan II University of Casablanca.",
                  src:"anas.png",},
                {name:"Omar BOUATTANE",cv:"Director of the Higher Normal School of Technical Education of Mohammedia",
                  src:"omar.png",},
                {name:"El M’Kaddem Kheddioui",cv:"Vice-President, in charge of Partnership, Cooperation and Development of the Hassan II University of Casablanca. Researcher Lecturer at the Faculty of Sciences and Techniques of Mohammedia of UH2C, Department of Electrical Engineering. Director of the Research Laboratory of Atmospheric Physics, Materials and Modeling (LPAMM), FSTM. Vice-president of the GreenTIC Research Center of UH2C. Co-initiator and coordinator of the e-douar project.",
                  src:"kaddem.png",},
                {name:"Khalid Safir",cv:"Wali, Director General of Territorial Collectivities.",
                  src:"safir.png"},
                {name:"Mohammed Khalil",cv:"Digitalization Officer to the President of the Hassan II University of Casablanca.",
                  src:"mohammed.png"},
                {name:"Driss Abbadi",cv:"Dean of the Faculty of Legal, Economic and Social Sciences Aïn Sbâa of the Hassan II University of Casablanca.",src:"driss.png",},
                {name:"Hans Martin Neumann",cv:"Smart City Program Coordinator - Austrian Institute of Technology",
                  src:"hans.png"},
                {name:"Abdelkader Gonegai",cv:"Dean of the Faculty of Letters and Human Sciences Ben M'Sik of the Hassan II University of Casablanca.",
                  src:"abdelkader.png",},
                {name:"Mehdi Alaoui",cv:"Vice-president of APEBI(The Tech federation of morocco).President of Hack & Pitch association.Founder of LaStartupFactory.",
                  src:"amehdi.png",}, 
                {name:"Mohammed Talbi",cv:"Dean of the Ben M'Sik Faculty of Sciences of the Hassan II University of Casablanca.",
                  src:"mohammedt.png"},
                {name:"Mohamed Amine Souissi",cv:"Head of the Digital Transformation Division - Direction of Skills Development and Digital Transformation - DGCT.",
                  src:"amine.png",},
                {name:"Danielle Pailler",cv:"Maghreb Director at the Agence Universitaire de la Francophonie.",
                  src:"danielle.png",},
                {name:"Annick Vignes",cv:"Research Director in Economics and Professor at the Ecole Nationale des Ponts et Chaussées (Paris).",
                  src:"annick.png",},
                {name:"Najib Ouradi",cv:"Director of the Casa Numeric BU within SDL Casablanca Prestations. After following the mission of developing the Digital Transformation Master Plan, its BU has been implementing it since 2018.",
                  src:"najib.png",},
                {name:"Zouheir Lakhdissi",cv:"CEO of Dial Technologies.Digital entrepreneur, consultant and international expert in the field of digital innovation.",
                  src:"zouheir.png",},
                {name:"Brahim Bachirat",cv:"Head of the Governance Promotion Division -Direction of Skills Development and Digital Transformation - DGCT.",src:"brahim.png",},
                {name:"Fayçal Benachou",cv:"General Manager of Ribatis, in chargeof the implementation and operation of the Rokhas.ma platform as part of a Public Private Partnership.",src:"faysal.png",},
                {name:"Anas Benouahoud",cv:"Head of Support Department for Public Bodies - Electronic Government Department E-GOV - Digital Development Agency.",src:"benouahoud.png",},
                {name:"Salaheddine Mechkouri",cv:"Head of the applications department of the administration of territorial collectivities - Direction of Skills Development and Digital Transformation - DGCT.",src:"mechkouri.png",},
                {name:"Sanae Belatiq",cv:"Head of Administrative Control - Division of Local Institutions - Directorate of Local Institutions - DGCT",src:"belatiq.png",},
                {name:"Ahmed Chebak",cv:"Professor of Electrical Engineering and Electromechanics at UM6P and Educational Director of the Green Tech Institute.",src:"chebak.png",},
                {name:"Essaaidi Mohamed",cv:"IEEE Senior Member and a Professor at ENSIAS, Mohammed V University in Rabat.",src:"essaaidi.png",},
                {name:"Hassan Yakubu",cv:"Analyst at the School of Architecture, Planning & Design-UM6P.",src:"yakubu.png",},
                {name:"Abdelaaziz Omari",cv:"President of the Council of the city of Casablanca.",
                  src:"omari.png"},
                {name:"Piero Scaruffi",cv:"President of the Silicon Valley Artificial Intelligence Research Institute.",
                  src:"piero.png"},
                {name:"Huê-Tâm Jamme",cv:"Assistant Professor of Urban Planning ,School of Geographical Sciences and Urban Planning, Arizona State University-USA.",
                  src:"jamme.png"},
                {name:"Alex Black",cv:"Economic Officer at United States Consulate General Casablanca.",
                  src:"alex.png"},
                {name:"Mohamed Faïçal Nebri",cv:"Head of Strategy, Development, Cooperation & Communication Departement -ADD",
                  src:"nebri.png"},
                {name:"Levent Gurgen ",cv:"President of the Urban Technology Alliance.",
                  src:"urgen.png"},
                {name:"Said Ahmidouch",cv:"Wali of the Casablanca Settat Region.",
                  src:"ahmidouch.png"},
                {name:"Nouzha Bouchareb",cv:"Minister of National Planning, Urban Planning, Housing and City Policy.",
                  src:"bouchareb.png"},
                {name:"Ismail Hammoumi",cv:"Research engineer at School of Architecture, Planning and Design -Mohammed VI Polytechnic University.",
                  src:"hammoumi.png"},
                {name:"Khaoula Benaomar",cv:"Architect-Urban Planner of the National School of Architecture of Rabat.",
                  src:"benaomar.png"},
                {name:"Nour-Eddin El Faouzi",cv:"Professor of Intelligent Mobility and Intelligent Transport Systems and Deputy Director of the Components and Systems Department at Gustave Eiffel University.",
                  src:"faouzi.png"},
                {name:"Mohamed Jouahri",cv:"General Manager of Casablanca Event and Animation.",
                  src:"mohamed.png"},
                {name:"Hakima Fasly",cv:"Vice-President of the Council of the City of Casablanca",
                  src:"hakima.png"},
                {name:"Aawatif Hayar",cv:"President of Hassan II University of Casablanca.",
                  src:"awatif.png",},
                {name:"Hassan Radoine",cv:"Director School of Architecture, Planning and Design of Mohammed VI Polytechnic University.",
                  src:"hassan.png",},
                {name:"Fabienne Goux-Baudiment",cv:"Doctor in social sciences and prospectivist.",
                  src:"fabien.png"},
                {name:"Cathal O'Madagain",cv:"Scientific director and assistant professor at the School of Collective Intelligence, UM6P. PhD in Philosophy from the University of Toronto.",
                  src:"cathal.png",},
                {name:"Remy Sietchiping",cv:"Chief of Policy, Legislation and Governance Section within the Urban Practices Branch of UN-Habitat. Ph.D in Geography from the University of Melbourne, Australia.",
                  src:"remy.png",},
                {name:"Monceyf Fadili",cv:"International expert in urban planning and territorial development.Former UN-Habitat Advisor.",
                  src:"monceyf.png",},
                {name:"Tridib Banerjee",cv:"Professor Emeritus of Public Policy, University of Southern California-USA.",
                  src:"tridib.png"},
                {name:"Rachel Armstrong",cv:"Professor of Experimental Architecture, University of Newcastle and Visiting Professor in the Department of Architecture, KU Leuven, Belgium.",
                  src:"rachel.png",},
                {name:"Giulio Verdini",cv:"Reader at the School of Architecture and Cities of the University of Westminster and Director of the BA Designing Cities: Planning and Architecture. He is also Visiting Professor at Mohammed VI Polytechnic University of Ben Guerir, in Morocco.",
                  src:"giulio.png",},
                {name:"Carlo Alberini",cv:"Architect and Urban Planner at Mohammed VI Polytechnic University with a PhD in Ports planning and waterfronts regeneration projects. He was a Fellow and Professor of Town Planning, Urban History, and Urban Management at the School of Architecture of Genoa and Florence.",
                  src:"carlo.png",},
                {name:"Matthew Hardy",cv:"Professor at Oxford University on the Sustainable Urban Development programme  and is Senior Lecturer and Direcor of Studies in Architecture and Urbanism at the Prince’s Foundation for Building Community.",
                  src:"matthew.png",},
                {name:"Saifur Rahman",cv:" Founding director of the Advanced Research Institute (www.ari.vt.edu) at Virginia Tech, USA where he is the Joseph R. Loring professor of electrical and computer engineering. He also directs the Center for Energy and the Global Environment (www.ceage.vt.edu). He is a Life Fellow of the IEEE and an IEEE Millennium Medal winner.",
                  src:"saifur.png",},
                {name:"Karima Echihabi",cv:"Research professor at the School of Computer Science of the Mohammed VI Polytechnic University in Morocco (UM6P). Her research interests are in data analysis, data series management and machine learning.",
                  src:"karima.png",},
                {name:"Hicham Bahi",cv:"Assistant Professor at the School of Architecture, Planning and Design, UM6P and holds a PhD in GIS and Remote Sensing.  He is among others the coordinator of the Territorial Performance Observatory project, the coordinator of doctoral training program of SAP+D and research team member of the urban metabolism project conducted jointly with MIT",
                  src:"hicham.png",},
                {name:"Mehdi Boukhari",cv:"Editor-in-chief of Editions Economiques, in charge of the Eco section of television news at 2M TV.",
                  src:"mehdi.png",}, 
                {name:"Lou Vasta",cv:"Lou Vasta, Founder & CEO, Vasta & Associates, Inc., CHICAGO, USA",
                  src:"lou.png",},
                {name:"Lamiae Benmakhlouf",cv:"Managing Director of MITC (Moroccan Information Technopark Company), Ms. Lamia Benmakhlouf has been working for 20 years in supporting entrepreneurship and innovation in high added value sectors.",
                  src:"lamiae.png",},
                {name:"Nicolas J.A. Buchoud",cv:"President of the Cercle Grand Paris for Sustainable Investment, co-founder of Renaissance Urbaine",
                  src:"nicolas.png",},
                {name:"Agnès Jullien",cv:"Vice- president international of Université Gustave Eiffel.Executive Director of the Forum of European Road Laboratories.",
                  src:"agnes.png"},
                {name:"Anass Kettani",cv:"Director of the Integration and Entrepreneurship Pole at Hassan II University in Casablanca. Deputy Director of the Biology and Health laboratory, Faculty of Sciences Ben Msik, Casablanca. Professor of Higher Education Hassan II University of Casablanca.",
                  src:"anas.png",},
                {name:"Omar BOUATTANE",cv:"Director of the Higher Normal School of Technical Education of Mohammedia",
                  src:"omar.png",},
                {name:"El M’Kaddem Kheddioui",cv:"Vice-President, in charge of Partnership, Cooperation and Development of the Hassan II University of Casablanca. Researcher Lecturer at the Faculty of Sciences and Techniques of Mohammedia of UH2C, Department of Electrical Engineering. Director of the Research Laboratory of Atmospheric Physics, Materials and Modeling (LPAMM), FSTM. Vice-president of the GreenTIC Research Center of UH2C. Co-initiator and coordinator of the e-douar project.",
                  src:"kaddem.png",},
                {name:"Khalid Safir",cv:"Wali, Director General of Territorial Collectivities.",
                  src:"safir.png"},
                {name:"Mohammed Khalil",cv:"Digitalization Officer to the President of the Hassan II University of Casablanca.",
                  src:"mohammed.png"},
                {name:"Driss Abbadi",cv:"Dean of the Faculty of Legal, Economic and Social Sciences Aïn Sbâa of the Hassan II University of Casablanca.",src:"driss.png",},
                {name:"Hans Martin Neumann",cv:"Smart City Program Coordinator - Austrian Institute of Technology",
                  src:"hans.png"},
                {name:"Abdelkader Gonegai",cv:"Dean of the Faculty of Letters and Human Sciences Ben M'Sik of the Hassan II University of Casablanca.",
                  src:"abdelkader.png",},
                {name:"Mehdi Alaoui",cv:"Vice-president of APEBI(The Tech federation of morocco).President of Hack & Pitch association.Founder of LaStartupFactory.",
                  src:"amehdi.png",}, 
                {name:"Mohammed Talbi",cv:"Dean of the Ben M'Sik Faculty of Sciences of the Hassan II University of Casablanca.",
                  src:"mohammedt.png"},
                {name:"Mohamed Amine Souissi",cv:"Head of the Digital Transformation Division - Direction of Skills Development and Digital Transformation - DGCT.",
                  src:"amine.png",},
                {name:"Danielle Pailler",cv:"Maghreb Director at the Agence Universitaire de la Francophonie.",
                  src:"danielle.png",},
                {name:"Annick Vignes",cv:"Research Director in Economics and Professor at the Ecole Nationale des Ponts et Chaussées (Paris).",
                  src:"annick.png",},
                {name:"Najib Ouradi",cv:"Director of the Casa Numeric BU within SDL Casablanca Prestations. After following the mission of developing the Digital Transformation Master Plan, its BU has been implementing it since 2018.",
                  src:"najib.png",},
                {name:"Zouheir Lakhdissi",cv:"CEO of Dial Technologies.Digital entrepreneur, consultant and international expert in the field of digital innovation.",
                  src:"zouheir.png",},
                {name:"Brahim Bachirat",cv:"Head of the Governance Promotion Division -Direction of Skills Development and Digital Transformation - DGCT.",src:"brahim.png",},
                {name:"Fayçal Benachou",cv:"General Manager of Ribatis, in chargeof the implementation and operation of the Rokhas.ma platform as part of a Public Private Partnership.",src:"faysal.png",},
                {name:"Anas Benouahoud",cv:"Head of Support Department for Public Bodies - Electronic Government Department E-GOV - Digital Development Agency.",src:"benouahoud.png",},
                {name:"Salaheddine Mechkouri",cv:"Head of the applications department of the administration of territorial collectivities - Direction of Skills Development and Digital Transformation - DGCT.",src:"mechkouri.png",},
                {name:"Sanae Belatiq",cv:"Head of Administrative Control - Division of Local Institutions - Directorate of Local Institutions - DGCT",src:"belatiq.png",},
                {name:"Ahmed Chebak",cv:"Professor of Electrical Engineering and Electromechanics at UM6P and Educational Director of the Green Tech Institute.",src:"chebak.png",},
                {name:"Essaaidi Mohamed",cv:"IEEE Senior Member and a Professor at ENSIAS, Mohammed V University in Rabat.",src:"essaaidi.png",},
                {name:"Hassan Yakubu",cv:"Analyst at the School of Architecture, Planning & Design-UM6P.",src:"yakubu.png",},
                {name:"Abdelaaziz Omari",cv:"President of the Council of the city of Casablanca.",
                  src:"omari.png"},
                {name:"Piero Scaruffi",cv:"President of the Silicon Valley Artificial Intelligence Research Institute.",
                  src:"piero.png"},
                {name:"Huê-Tâm Jamme",cv:"Assistant Professor of Urban Planning ,School of Geographical Sciences and Urban Planning, Arizona State University-USA.",
                  src:"jamme.png"},
                {name:"Alex Black",cv:"Economic Officer at United States Consulate General Casablanca.",
                  src:"alex.png"},
                {name:"Mohamed Faïçal Nebri",cv:"Head of Strategy, Development, Cooperation & Communication Departement -ADD",
                  src:"nebri.png"},
                {name:"Levent Gurgen ",cv:"President of the Urban Technology Alliance.",
                  src:"urgen.png"},
                {name:"Said Ahmidouch",cv:"Wali of the Casablanca Settat Region.",
                  src:"ahmidouch.png"},
                {name:"Nouzha Bouchareb",cv:"Minister of National Planning, Urban Planning, Housing and City Policy.",
                  src:"bouchareb.png"},
                {name:"Ismail Hammoumi",cv:"Research engineer at School of Architecture, Planning and Design -Mohammed VI Polytechnic University.",
                  src:"hammoumi.png"},
                {name:"Khaoula Benaomar",cv:"Architecte-Urbaniste de l'Ecole Nationale d'Architecture de Rabat.",
                  src:"benaomar.png"},
                {name:"Nour-Eddin El Faouzi",cv:"Professor of Intelligent Mobility and Intelligent Transport Systems and Deputy Director of the Components and Systems Department at Gustave Eiffel University.",
                  src:"faouzi.png"},
                 {name:"Mohamed Jouahri",cv:"General Manager of Casablanca Event and Animation.",
                  src:"mohamed.png"},
                {name:"Hakima Fasly",cv:"Vice-President of the Council of the City of Casablanca",
                  src:"hakima.png"},
                {name:"Aawatif Hayar",cv:"President of Hassan II University of Casablanca.",
                  src:"awatif.png",},
                {name:"Hassan Radoine",cv:"Director School of Architecture, Planning and Design of Mohammed VI Polytechnic University.",
                  src:"hassan.png",},
                {name:"Fabienne Goux-Baudiment",cv:"Doctor in social sciences and prospectivist.",
                  src:"fabien.png"},
                {name:"Cathal O'Madagain",cv:"Scientific director and assistant professor at the School of Collective Intelligence, UM6P. PhD in Philosophy from the University of Toronto.",
                  src:"cathal.png",},
                {name:"Remy Sietchiping",cv:"Chief of Policy, Legislation and Governance Section within the Urban Practices Branch of UN-Habitat. Ph.D in Geography from the University of Melbourne, Australia.",
                  src:"remy.png",},
                {name:"Monceyf Fadili",cv:"International expert in urban planning and territorial development.Former UN-Habitat Advisor.",
                  src:"monceyf.png",},
                {name:"Tridib Banerjee",cv:"Professor Emeritus of Public Policy, University of Southern California-USA.",
                  src:"tridib.png"},
                {name:"Rachel Armstrong",cv:"Professor of Experimental Architecture, University of Newcastle and Visiting Professor in the Department of Architecture, KU Leuven, Belgium.",
                  src:"rachel.png",},
                {name:"Giulio Verdini",cv:"Reader at the School of Architecture and Cities of the University of Westminster and Director of the BA Designing Cities: Planning and Architecture. He is also Visiting Professor at Mohammed VI Polytechnic University of Ben Guerir, in Morocco.",
                  src:"giulio.png",},
                {name:"Carlo Alberini",cv:"Architect and Urban Planner at Mohammed VI Polytechnic University with a PhD in Ports planning and waterfronts regeneration projects. He was a Fellow and Professor of Town Planning, Urban History, and Urban Management at the School of Architecture of Genoa and Florence.",
                  src:"carlo.png",},
                {name:"Matthew Hardy",cv:"Professor at Oxford University on the Sustainable Urban Development programme  and is Senior Lecturer and Direcor of Studies in Architecture and Urbanism at the Prince’s Foundation for Building Community.",
                  src:"matthew.png",},
                {name:"Saifur Rahman",cv:" Founding director of the Advanced Research Institute (www.ari.vt.edu) at Virginia Tech, USA where he is the Joseph R. Loring professor of electrical and computer engineering. He also directs the Center for Energy and the Global Environment (www.ceage.vt.edu). He is a Life Fellow of the IEEE and an IEEE Millennium Medal winner.",
                  src:"saifur.png",},
                {name:"Karima Echihabi",cv:"Research professor at the School of Computer Science of the Mohammed VI Polytechnic University in Morocco (UM6P). Her research interests are in data analysis, data series management and machine learning.",
                  src:"karima.png",},
                {name:"Hicham Bahi",cv:"Assistant Professor at the School of Architecture, Planning and Design, UM6P and holds a PhD in GIS and Remote Sensing.  He is among others the coordinator of the Territorial Performance Observatory project, the coordinator of doctoral training program of SAP+D and research team member of the urban metabolism project conducted jointly with MIT",
                  src:"hicham.png",},
                {name:"Mehdi Boukhari",cv:"Editor-in-chief of Editions Economiques, in charge of the Eco section of television news at 2M TV.",
                  src:"mehdi.png",}, 
                {name:"Lou Vasta",cv:"Lou Vasta, Founder & CEO, Vasta & Associates, Inc., CHICAGO, USA",
                  src:"lou.png",},
                {name:"Lamiae Benmakhlouf",cv:"Managing Director of MITC (Moroccan Information Technopark Company), Ms. Lamia Benmakhlouf has been working for 20 years in supporting entrepreneurship and innovation in high added value sectors.",
                  src:"lamiae.png",},
                {name:"Nicolas J.A. Buchoud",cv:"President of the Cercle Grand Paris for Sustainable Investment, co-founder of Renaissance Urbaine",
                  src:"nicolas.png",},
                {name:"Agnès Jullien",cv:"Vice- president international of Université Gustave Eiffel.Executive Director of the Forum of European Road Laboratories.",
                  src:"agnes.png"},
                {name:"Anass Kettani",cv:"Director of the Integration and Entrepreneurship Pole at Hassan II University in Casablanca. Deputy Director of the Biology and Health laboratory, Faculty of Sciences Ben Msik, Casablanca. Professor of Higher Education Hassan II University of Casablanca.",
                  src:"anas.png",},
                {name:"Omar BOUATTANE",cv:"Director of the Higher Normal School of Technical Education of Mohammedia",
                  src:"omar.png",},
                {name:"El M’Kaddem Kheddioui",cv:"Vice-President, in charge of Partnership, Cooperation and Development of the Hassan II University of Casablanca. Researcher Lecturer at the Faculty of Sciences and Techniques of Mohammedia of UH2C, Department of Electrical Engineering. Director of the Research Laboratory of Atmospheric Physics, Materials and Modeling (LPAMM), FSTM. Vice-president of the GreenTIC Research Center of UH2C. Co-initiator and coordinator of the e-douar project.",
                  src:"kaddem.png",},
                {name:"Khalid Safir",cv:"Wali, Director General of Territorial Collectivities.",
                  src:"safir.png"},
                {name:"Mohammed Khalil",cv:"Digitalization Officer to the President of the Hassan II University of Casablanca.",
                  src:"mohammed.png"},
                {name:"Driss Abbadi",cv:"Dean of the Faculty of Legal, Economic and Social Sciences Aïn Sbâa of the Hassan II University of Casablanca.",src:"driss.png",},
                {name:"Hans Martin Neumann",cv:"Smart City Program Coordinator - Austrian Institute of Technology",
                  src:"hans.png"},
                {name:"Abdelkader Gonegai",cv:"Dean of the Faculty of Letters and Human Sciences Ben M'Sik of the Hassan II University of Casablanca.",
                  src:"abdelkader.png",},
                {name:"Mehdi Alaoui",cv:"Vice-president of APEBI(The Tech federation of morocco).President of Hack & Pitch association.Founder of LaStartupFactory.",
                  src:"amehdi.png",}, 
                {name:"Mohammed Talbi",cv:"Dean of the Ben M'Sik Faculty of Sciences of the Hassan II University of Casablanca.",
                  src:"mohammedt.png"},
                {name:"Mohamed Amine Souissi",cv:"Head of the Digital Transformation Division - Direction of Skills Development and Digital Transformation - DGCT.",
                  src:"amine.png",},
                {name:"Danielle Pailler",cv:"Maghreb Director at the Agence Universitaire de la Francophonie.",
                  src:"danielle.png",},
                {name:"Annick Vignes",cv:"Research Director in Economics and Professor at the Ecole Nationale des Ponts et Chaussées (Paris).",
                  src:"annick.png",},
                {name:"Najib Ouradi",cv:"Director of the Casa Numeric BU within SDL Casablanca Prestations. After following the mission of developing the Digital Transformation Master Plan, its BU has been implementing it since 2018.",
                  src:"najib.png",},
                {name:"Zouheir Lakhdissi",cv:"CEO of Dial Technologies.Digital entrepreneur, consultant and international expert in the field of digital innovation.",
                  src:"zouheir.png",},
                {name:"Brahim Bachirat",cv:"Head of the Governance Promotion Division -Direction of Skills Development and Digital Transformation - DGCT.",src:"brahim.png",},
                {name:"Fayçal Benachou",cv:"General Manager of Ribatis, in chargeof the implementation and operation of the Rokhas.ma platform as part of a Public Private Partnership.",src:"faysal.png",},
                {name:"Anas Benouahoud",cv:"Head of Support Department for Public Bodies - Electronic Government Department E-GOV - Digital Development Agency.",src:"benouahoud.png",},
                {name:"Salaheddine Mechkouri",cv:"Head of the applications department of the administration of territorial collectivities - Direction of Skills Development and Digital Transformation - DGCT.",src:"mechkouri.png",},
                {name:"Sanae Belatiq",cv:"Head of Administrative Control - Division of Local Institutions - Directorate of Local Institutions - DGCT",src:"belatiq.png",},
                {name:"Ahmed Chebak",cv:"Professor of Electrical Engineering and Electromechanics at UM6P and Educational Director of the Green Tech Institute.",src:"chebak.png",},
                {name:"Essaaidi Mohamed",cv:"IEEE Senior Member and a Professor at ENSIAS, Mohammed V University in Rabat.",src:"essaaidi.png",},
                {name:"Hassan Yakubu",cv:"Analyst at the School of Architecture, Planning & Design-UM6P.",src:"yakubu.png",},
                {name:"Abdelaaziz Omari",cv:"President of the Council of the city of Casablanca.",
                  src:"omari.png"},
                {name:"Piero Scaruffi",cv:"President of the Silicon Valley Artificial Intelligence Research Institute.",
                  src:"piero.png"},
                {name:"Huê-Tâm Jamme",cv:"Assistant Professor of Urban Planning ,School of Geographical Sciences and Urban Planning, Arizona State University-USA.",
                  src:"jamme.png"},
                {name:"Alex Black",cv:"Economic Officer at United States Consulate General Casablanca.",
                  src:"alex.png"},
                {name:"Mohamed Faïçal Nebri",cv:"Head of Strategy, Development, Cooperation & Communication Departement -ADD",
                  src:"nebri.png"},
                {name:"Levent Gurgen ",cv:"President of the Urban Technology Alliance.",
                  src:"urgen.png"},
                  {name:"Said Ahmidouch",cv:"Wali of the Casablanca Settat Region.",
                  src:"ahmidouch.png"},
                {name:"Nouzha Bouchareb",cv:"Minister of National Planning, Urban Planning, Housing and City Policy.",
                  src:"bouchareb.png"},
                {name:"Ismail Hammoumi",cv:"Research engineer at School of Architecture, Planning and Design -Mohammed VI Polytechnic University.",
                  src:"hammoumi.png"},
                {name:"Khaoula Benaomar",cv:"Architecte-Urbaniste de l'Ecole Nationale d'Architecture de Rabat.",
                  src:"benaomar.png"},
                {name:"Nour-Eddin El Faouzi",cv:"Professor of Intelligent Mobility and Intelligent Transport Systems and Deputy Director of the Components and Systems Department at Gustave Eiffel University.",
                  src:"faouzi.png"},
            ],
            responsive: [
                [200, 1],[767, 2],[1000, 4]
            ],
        }
    },
    props: ['slideshow'],
    components: {
        Carousel,
        Slide
    },
    methods: {
    },
}
</script>
<style>
.v-card--reveal {
  align-items: center;
  bottom: 0;
  justify-content: center;
  position: absolute;
  width: 100%;
}
.v-card--reveal-first {
  align-items: center;
  top: 120px;
  justify-content: center;
  position: absolute;
  width: 100%;
}
</style>